In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.6.0


In [3]:
scalar = tf.constant(42)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [4]:
scalar.ndim

0

In [6]:
vector = tf.constant([42, 42])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 42], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[42,24],
                      [42,24]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [42, 24]], dtype=int32)>

In [9]:
matrix.ndim

2

In [12]:
matrix = tf.constant([[42,24],
                      [42,24]], dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[42., 24.],
       [42., 24.]], dtype=float16)>

In [13]:
changeable_tensor = tf.Variable([2,3])
unchangeable_tensor = tf.constant([2,3])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>)

In [14]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [16]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 3], dtype=int32)>

In [17]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [18]:
random_1 = tf.random.Generator.from_seed(23).normal(shape=(2,3))
random_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
       [ 0.4457582 ,  0.10944034, -0.8035768 ]], dtype=float32)>

In [21]:
not_shuffled = tf.constant([[2,343], [2342,3], [3452,334]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[   2,  343],
       [2342,    3],
       [3452,  334]], dtype=int32)>

In [22]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3452,  334],
       [2342,    3],
       [   2,  343]], dtype=int32)>

In [23]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [24]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [25]:
import numpy as np

In [27]:
numpy_A = np.arange(1,25)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [28]:
tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [31]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[0:2,:,:,:]

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
rank_3_tensor = tf.random.Generator.from_seed(42).normal(shape=(2,3,4))
rank_3_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],

       [[-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
        [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]]],
      dtype=float32)>

In [37]:
rank_4_tensor = rank_3_tensor[..., tf.newaxis]
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 1), dtype=float32, numpy=
array([[[[-0.7565803 ],
         [-0.06854702],
         [ 0.07595026],
         [-1.2573844 ]],

        [[-0.23193763],
         [-1.8107855 ],
         [ 0.09988727],
         [-0.50998646]],

        [[-0.7535805 ],
         [-0.57166284],
         [ 0.1480774 ],
         [-0.23362993]]],


       [[[-0.3522796 ],
         [ 0.40621263],
         [-1.0523509 ],
         [ 1.2054597 ]],

        [[ 1.6874489 ],
         [-0.4462975 ],
         [-2.3410842 ],
         [ 0.99009085]],

        [[-0.0876323 ],
         [-0.635568  ],
         [-0.6161736 ],
         [-1.9441465 ]]]], dtype=float32)>

In [39]:
tf.expand_dims(rank_3_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
         [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
         [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],

        [[-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
         [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
         [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]]]],
      dtype=float32)>

In [42]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [41]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [44]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [45]:
X @ Y

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [46]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [47]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [48]:
tf.constant([2.,3.]).dtype

tf.float32