In [65]:
import tensorflow as tf

In [66]:
print(tf.__version__)

2.6.0


In [67]:
scalar = tf.constant(42)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [68]:
scalar.ndim

0

In [69]:
vector = tf.constant([42, 42])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 42], dtype=int32)>

In [70]:
vector.ndim

1

In [71]:
matrix = tf.constant([[42,24],
                      [42,24]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 24],
       [42, 24]], dtype=int32)>

In [72]:
matrix.ndim

2

In [73]:
matrix = tf.constant([[42,24],
                      [42,24]], dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[42., 24.],
       [42., 24.]], dtype=float16)>

In [74]:
changeable_tensor = tf.Variable([2,3])
unchangeable_tensor = tf.constant([2,3])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>)

In [75]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 3], dtype=int32)>

In [76]:
random_1 = tf.random.Generator.from_seed(23).normal(shape=(2,3))
random_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
       [ 0.4457582 ,  0.10944034, -0.8035768 ]], dtype=float32)>

In [77]:
not_shuffled = tf.constant([[2,343], [2342,3], [3452,334]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[   2,  343],
       [2342,    3],
       [3452,  334]], dtype=int32)>

In [78]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3452,  334],
       [2342,    3],
       [   2,  343]], dtype=int32)>

In [79]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [80]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [81]:
import numpy as np

In [82]:
numpy_A = np.arange(1,25)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [83]:
tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [84]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [85]:
rank_4_tensor[0:2,:,:,:]

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [86]:
rank_3_tensor = tf.random.Generator.from_seed(42).normal(shape=(2,3,4))
rank_3_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],

       [[-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
        [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]]],
      dtype=float32)>

In [87]:
rank_4_tensor = rank_3_tensor[..., tf.newaxis]
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 1), dtype=float32, numpy=
array([[[[-0.7565803 ],
         [-0.06854702],
         [ 0.07595026],
         [-1.2573844 ]],

        [[-0.23193763],
         [-1.8107855 ],
         [ 0.09988727],
         [-0.50998646]],

        [[-0.7535805 ],
         [-0.57166284],
         [ 0.1480774 ],
         [-0.23362993]]],


       [[[-0.3522796 ],
         [ 0.40621263],
         [-1.0523509 ],
         [ 1.2054597 ]],

        [[ 1.6874489 ],
         [-0.4462975 ],
         [-2.3410842 ],
         [ 0.99009085]],

        [[-0.0876323 ],
         [-0.635568  ],
         [-0.6161736 ],
         [-1.9441465 ]]]], dtype=float32)>

In [88]:
tf.expand_dims(rank_3_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
         [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
         [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],

        [[-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
         [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
         [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]]]],
      dtype=float32)>

In [89]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [90]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [91]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [92]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [93]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [94]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [95]:
tf.constant([2.,3.]).dtype

tf.float32

## Aggregating tensors

In [96]:
tensor1 = tf.constant([7, -10])
tf.abs(tensor1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [99]:
tensor_2 = tf.constant(np.random.randint(0, 100, size=(50)))
tensor_2

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 7, 27,  5, 21, 34, 72, 80, 92, 94, 93, 43, 13, 91, 70, 44,  6, 56,
       52,  9, 24, 39, 77, 42, 35, 81, 58,  2, 74, 82, 26, 13, 89, 29, 29,
       52, 44, 10, 67,  0, 55, 81, 43, 30, 75,  4, 64, 61, 72, 61, 50])>

In [100]:
tf.reduce_min(tensor_2)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [101]:
tf.reduce_max(tensor_2)

<tf.Tensor: shape=(), dtype=int64, numpy=94>

In [102]:
import tensorflow_probability as tfp

In [103]:
tfp.stats.variance(tensor_2)

<tf.Tensor: shape=(), dtype=int64, numpy=799>

In [106]:
tf.math.reduce_variance(tf.cast(tensor_2, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=798.9264>

## Positional maximum and minimum

In [111]:
tf.random.set_seed(78)
tensor_3 = tf.random.uniform(shape=[50])
tensor_3

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.5207231 , 0.03446662, 0.6855806 , 0.6403918 , 0.3417244 ,
       0.45266557, 0.561218  , 0.2637217 , 0.75090647, 0.06268799,
       0.35305107, 0.9579406 , 0.07038355, 0.96618915, 0.9847739 ,
       0.34914303, 0.9182358 , 0.87256575, 0.7383952 , 0.30763865,
       0.1823287 , 0.02723598, 0.98718286, 0.56463087, 0.5899576 ,
       0.35117292, 0.14034915, 0.12389338, 0.34338593, 0.2850032 ,
       0.28120816, 0.7067089 , 0.09791291, 0.3415208 , 0.13247514,
       0.84854853, 0.06742489, 0.04190516, 0.3884064 , 0.9785038 ,
       0.9802002 , 0.71259594, 0.13942444, 0.28875315, 0.65633297,
       0.12442577, 0.29199982, 0.7735796 , 0.3678118 , 0.5638118 ],
      dtype=float32)>

In [113]:
# find the positional max
tf.argmax(tensor_3)

<tf.Tensor: shape=(), dtype=int64, numpy=22>

In [114]:
tensor_3[tf.argmax(tensor_3)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.98718286>

In [118]:
tensor_4 = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
tensor_4

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.19066143, 0.29487264, 0.9825661 , 0.7770307 , 0.4709115 ,
           0.7720171 , 0.3555503 , 0.9113327 , 0.37434042, 0.84045386,
           0.02311075, 0.73201907, 0.65237904, 0.5596782 , 0.5826863 ,
           0.66730213, 0.5778409 , 0.8293637 , 0.74196005, 0.01009548,
           0.9644629 , 0.29172993, 0.92483175, 0.09383464, 0.6653248 ,
           0.9478948 , 0.80430496, 0.39738715, 0.79175174, 0.04125404,
           0.2834704 , 0.03467679, 0.8231821 , 0.7177837 , 0.8791219 ,
           0.58193827, 0.3298489 , 0.21321046, 0.37791204, 0.24021888,
           0.5817684 , 0.2611401 , 0.8817433 , 0.18647993, 0.43926287,
           0.75671184, 0.39905274, 0.23592246, 0.26444805, 0.24519384]]]]],
      dtype=float32)>

In [119]:
tensor_4.ndim

5

In [120]:
tensor_4 = tf.squeeze(tensor_4)

In [121]:
tensor_4.shape

TensorShape([50])

## one hot encoding

In [122]:
List_1 = [0, 1, 2, 3]

In [128]:
tf.one_hot(List_1, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>